### PR TITLE
Add API flag `retrieval_only` - retrieving ONLY contexts, no LLM invoked

### PR DESCRIPTION
**Pull request by rohan-uiuc**
Contexts are returned by default on non-streaming API. 
Added flag `retrieval_only`

### CODE REVIEW

**Comment by KastanDay** [comment]
My major request is to add this to the docs & example code on `/api`. 

Further, if reasonable, it would be great to add this to the non-streaming API by default.

**Review by KastanDay — APPROVED** [review]
My major request is to add this to the docs & example code on `/api`. 

Further, if reasonable, it would be great to add this to the non-streaming API by default.

**Comment by KastanDay** [comment]
@rohan-uiuc I'm having timeouts at around 20 seconds. 
CleanShot 2024-10-07 at 18 21 12@2x

**Comment by rohan-uiuc** [comment]
Yep, docs is next, starting that. 
RE:`it would be great to add this to the non-streaming API by default.` It is added to the non streaming API by default in the last commit.

**Comment by KastanDay** [comment]
Ok I modified the examples on `/api`
* Default to llama3.1 so that the 'copy and paste' works without modification. 
* Emphasize in writing that `GPT-4o-mini` is the best price/perf model. 
CleanShot 2024-10-08 at 12 42 21

**Comment by KastanDay** [comment]
Added a link to our docs page, too: 
CleanShot 2024-10-08 at 12 46 31

**Comment by KastanDay** [comment]
Ok that's a convincing argument. I agree with gpt-4o-mini perf being so much better that we should keep it default.

**Comment by rohan-uiuc** [comment]
Screenshot 2024-10-08 at 3 22 47 PM
Screenshot 2024-10-08 at 3 23 04 PM

This information is already available in the documentation.

**Comment by KastanDay** [comment]
> Screenshot 2024-10-08 at 3 22 47 PM Screenshot 2024-10-08 at 3 23 04 PM
> 
> This information is already available in the documentation.

Agree, but I still think it's worth a callout here. So I'm voting to keep it for now.

**Comment by rohan-uiuc** [comment]
> > Screenshot 2024-10-08 at 3 22 47 PM Screenshot 2024-10-08 at 3 23 04 PM
> > This information is already available in the documentation.
> 
> Agree, but I still think it's worth a callout here. So I'm voting to keep it for now.

Can we move this to a separate PR, do a review of the UI and then push this? I believe this PR is ready to merge without these changes. The new changes donot match fonts, increase the text by a lot on this page and are not related to the fix at all.

**Comment by KastanDay** [comment]
I like the black code formatting. I could make the contrast less intense if you insist. But we use it elsewhere.

CleanShot 2024-10-08 at 13 41 15

Let's just merge it as is. The styling isn't bad.

**Pull request merged**
