### PR TITLE
Fix Request Body over 4.5 MB

### PR DESCRIPTION
**Pull request by KastanDay**

### CODE REVIEW

**Comment by KastanDay** [comment]
TODO: Migrate all LLM /chat endpoints from `route` to standard server-to-server function calls. I did Ollama, but the others need it too. in App router.

**Comment by KastanDay** [comment]
@minump @rohan-uiuc This is fully tested and ready for final review and merge. 

I'm confident I fixed: 
* Ollama, Anthropic, OpenAI and Azure. 
* Ensured our UIUC.chat api still works with OpenAI and Ollama in both stream and non-stream. Didn't test Anthropic or Azure.

**Comment by minump** [comment]
@KastanDay This is awesome.. Thanks a ton for taking the time to fix the bug and putting this together..

**Comment by KastanDay** [comment]
My testing is complete. It works great. TODO (optionally): Support for Anthropic/Azure in the API.

**Comment by minump** [comment]
And i love the "bug Squashed" banner :D

**Comment by minump** [comment]
Screenshot 2024-11-12 at 3 06 40 PM

I did get a logConversationtoSupbase error - but it doesnt stop the response- guess it just doesnt load the conversation to supabase. But thats a lower priority. Again thanks a ton.

**Comment by KastanDay** [comment]
> Screenshot 2024-11-12 at 3 06 40 PM
> 
> I did get a logConversationtoSupbase error - but it doesnt stop the response- guess it just doesnt load the conversation to supabase. But thats a lower priority. Again thanks a ton.

This is a known problem, caused by the same exact problem: body size is over 4.5 MB... It's because we're logging the entire conversation in a single request.... need to refactor into our modern `convo` + `messages` separate tables.

**Pull request merged**
