### PR TITLE
Course Ingest using url

### PR DESCRIPTION
**Pull request by rohan-uiuc**
Changes to add text input for ingesting mit, coursera courses or webscraping urls
Bugfix for persisting courseMetadata values on course visibility change and on upload files.

### CODE REVIEW

**Comment by rohan-uiuc** [comment]
Need to add some messages to explain the functionality. @KastanDay can you help with it?

**Comment by KastanDay** [comment]
investigating now…

**Comment by KastanDay** [comment]
If we ingest a website, you should create a "project" (formerly known as a "course") and redirect the user to /materials. 

TLDR: after clicking on "ingest/web-scrape" `router.push({course_name}/materials)`

**Comment by KastanDay** [comment]
Otherwise looks good. Tomorrow I will add `supported_filetypes.tsx` to the PR to update the logos.

**Comment by KastanDay** [comment]
If you have time, I'd love help fixing the `upsert` problem `on image upload` & `on email change`. thanks!

**Comment by KastanDay** [comment]
Oh thank u for this bugfix, that’ll be really helpful.

**Comment by KastanDay** [comment]
I tested & it's working: the bugfix to persist `baner_image_s3` and `course_intro_message`. Thank you.

**Comment by KastanDay** [comment]
Other major changes:
* Bugfix: post login redirect for /new page (including respecting the query param, if exists)
* Improve layout of QDrant storage by using mmap on recommended settings (configured outside of this PR, but necessary to support massive web scraping).

**Pull request merged**
