### PR TITLE
Major Feature: Tool Support

### PR DESCRIPTION
**Pull request by Maxwell-Lindsey**
We will publish docs to describe the usage in more detail on https://docs.uiuc.chat

1. Log convos to LangSmith for easier validation of prompt engineering of final prompts
2. Fix bug with saving conversation history when browser localStorage is full. 
3. Much improved design of /chat page - responsive design, fixed markdown support to include headers (and everything else).

### CODE REVIEW

**Comment by rohan-uiuc** [comment]
Screenshot 2024-06-04 at 7 12 23 PM

**Comment by KastanDay** [comment]
I tried and failed a few times to merge main and staging. 
In `ProjectFilesTable` you have to update `invalidateQueries` to use dictionary syntax. This is the good syntax: `invalidateQueries({ queryKey: ['documents', course_name] })`

But then I can't figure out why it throws errors all over, weird ones like `'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)`

**Review by KastanDay — APPROVED** [review]
Everything looks 100% ready to go. Thorough testing, it all looks fantastic. FINALLY MERGE!

**Review by rohan-uiuc — APPROVED** [review]
Looks fantastic, merging this!

CleanShot 2024-06-24 at 15 30 49

**Pull request merged**
