### PR TITLE
Add Magic Bell Notifications

### PR DESCRIPTION
**Pull request by KastanDay**
Nice and easy GUI composing interface. 

CleanShot 2023-12-19 at 15 07 12

### CODE REVIEW

**Comment by rohan-uiuc** [comment]
This looks great overall. 
Minor things: 
1. Can we create a test notification and try it out? Currently, I see none. 
2. Spacing of bell seems inconsistent with spacing of other Navbar buttons.

**Comment by rohan-uiuc** [comment]
This is amazing! I love Magic Bell notifications already. They feature will enhance user engagement and awareness of new updates.
Screenshot 2023-12-20 at 2 19 27 PM

**Comment by KastanDay** [comment]
> This is amazing! I love Magic Bell notifications already. They will enhance user engagement and awareness of new updates. Screenshot 2023-12-20 at 2 19 27 PM

Agree. Also, I made the custom "empty inbox" image using ChatGPT. I'm hosting it on CloudFlare R2 for super fast read times. I did S3 at first, but the image would load in like a 1990s dial-up internet connectionrouter. 

```typescript
images={{ emptyInboxUrl: 'https://assets.kastan.ai/minified_empty_chat_art.png' }}
```

**Comment by rohan-uiuc** [comment]
Yeah, this is awesome. The image loaded instantly!
Screenshot 2023-12-20 at 2 32 39 PM

**Pull request merged**
