### PR TITLE
Major Navbar redesign (copy Github/Vercel)

### PR DESCRIPTION
**Pull request by KastanDay**

### CODE REVIEW

**Comment by KastanDay** [comment]
Implement your main Navbar on `/materials` and `/query-analysis`

Separate navbar on the homepage (index) with only two buttons: `New` and `Login`.

**Comment by hanlily666** [comment]
> Implement your main Navbar on `/materials` and `/query-analysis`
> 
> Separate navbar on the homepage (index) with only two buttons: `New` and `Login`.

- add the main navbar on '/materials' and '/query-analysis' but when the active style only applies when I clicked on it. Need help to figure that out.
- add the separate navbar on the homepage. Have question about the login button

**Comment by KastanDay** [comment]
Thanks for this! I’ll review and see if I can advise on those. 

What exactly do you need from the Login button?

**Comment by hanlily666** [comment]
If i'm not logged in, I can still see the sign in button in the global header. I am not sure what is the difference between sign in and log in.

**Comment by KastanDay** [comment]
"Login" and "sign in" should be identical. Just different words for the same thing. 

When NOT signed in, you should see the "Sign in" button.
CleanShot 2023-09-12 at 20 23 36

When SIGNED in, you should see your profile picture instead. 
CleanShot 2023-09-12 at 20 23 58


Does that clarify everything? Or is there something more? Thanks for these questions, that’s a key performance indicator.

**Comment by hanlily666** [comment]
Should I delete the login one and put the "sign in" (global header) in the place of log in? It looks like this right now.
Screenshot 2023-09-12 at 10 27 22 PM

**Comment by KastanDay** [comment]
Yes, please use our existing "sign in" button/component because it's a special one that is built by Clerk. That same text will auto-transform into a profile picture when users are signed in.

Thanks! Please keep asking questions as much as possible. :)

**Comment by hanlily666** [comment]
Got it! That makes sense. :)

**Comment by hanlily666** [comment]
I think we should add the Navbar on the '/gpt4' page as well. I can do that after merging the current version, since I still have the old style on the gpt4 page.

**Comment by KastanDay** [comment]
Minor changes requested:

1. Can we add a tiny bit of padding between these buttons, and make the underline our classic purple color?
CleanShot 2023-09-22 at 11 29 58

2. Can we just bump up the `y` value of this buton on the home page? OR move it to the right side? I think it looks better on the right side than in the middle. It looks lonely here.. 
CleanShot 2023-09-22 at 11 31 35

**Comment by KastanDay** [comment]
This is our old chat page, before the major redesign. I'll merge the `main` branch into yours, then we can see how it looks.

CleanShot 2023-09-22 at 11 33 25

**Comment by KastanDay** [comment]
Thanks for these commits! I’ll merge this first thing on Monday, looking good.

**Comment by KastanDay** [comment]
TODO: 
* [ ] On `/index`, Remove bar from homepage (index.tsx). We'll use a simpler one instead. My trusted designer from Big Tech said the homepage shouldn’t have a navbar. It’s our landing/marketing page and it felt too busy with a navbar.
* [ ] On `/gpt4`, Only show Materials and Analysis buttons if the user is the Owner or Admin.
CleanShot 2023-09-29 at 15 16 30
 
 * [ ] For some reason, the buttons are not clickable when the user must enter an API key. This is really bad because often they want to enter the key directly on the /materials page. 

CleanShot 2023-09-29 at 15 18 02

The rest looks very good! Thank you! I like your clean code implementation of a list of tabs, and a variable selecting which is currently active. Nice!

**Comment by KastanDay** [comment]
@hanlily666 It's getting close, but we have a few bugs to work out.

1. Bigger problem: it looks like chatting is broken, when I try to chat, my initial message disappears, then all the messages disappear once the bot starts responding. 
2. It looks like we lost the course banner image in the /gpt4 page navbar, need that back.
3. Only show "Materials" and "analysis" if the current user is an owner/admin. 

CleanShot 2023-10-06 at 09 15 37

**Comment by KastanDay** [comment]
@hanlily666 It's getting close, but we have a few bugs to work out.

1. Bigger problem: it looks like chatting is broken, when I try to chat, my initial message disappears, then all the messages disappear once the bot starts responding. 
2. It looks like we lost the course banner image in the /gpt4 page navbar, need that back.
3. Only show "Materials" and "analysis" if the current user is an owner/admin. 
4. I think the all-caps text hurts readability. Neither Vercel or Github have all-caps navbars, let's use normal lower case. 

CleanShot 2023-10-06 at 09 15 37

**Review by KastanDay — COMMENTED** [review]
I requested a few changes.

**Comment by hanlily666** [comment]
It still has several issues with the ChatNavbar and ChatBar
- when the content overflows the page, the page scroll below the end of the page. There is extra space
Screenshot 2023-10-08 at 10 44 51 PM
- There is a bit edge coming out from the global header
Screenshot 2023-10-08 at 10 45 16 PM
- When I ask first question, the chatbar updates the message into the chatbar but cannot record second message I asked

**Comment by KastanDay** [comment]
Thanks for these commits and the screenshots in your update. Let’s talk in the meeting on monday about the best way to finish up.

**Comment by KastanDay** [comment]
I have a tip on where to fix the extra space on the bottom of the chat page. It’s in Chat.tsx, where we have a div of empty space

**Comment by KastanDay** [comment]
Woah it's looking super good! Great working on handing if the user is an Admin/Owner. 

Gotta fix the ChatBar bar not respecting the Sidebar. Most people have the sidebar open at all times. 
CleanShot 2023-10-13 at 11 41 24

**Comment by KastanDay** [comment]
Still has the wrong/old CSS for the Banner image. I really want the current Production resizing behavior.

CleanShot 2023-10-13 at 11 45 06

**Comment by hanlily666** [comment]
Oh thanks for noticing that! I will change these now.

**Pull request merged**
